name: CI-verification html

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]

jobs:
 test-html:
  runs-on: ubuntu-latest

  steps:
   - name: recuperation du code
     uses: actions/checkout@v4

   - name: verification syntaxe html
     uses: anishathalye/proof-html@v2
     with:
      directory: index.html
      ignore_favicon: true
