name: CI-verification html
on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]

jobs:
 test-html:
  runs-on: ubuntu-latest
  steps:
   -name: recuperation du code
    uses: actions/checkout@v3

   -name: verification syntaxe html
    uses: cyber3r-jak3/html5validator-action@v7.2.0
    with:
     root:
